### ISSUE TITLE
I do this for learning Not for Scaming Mr

### ISSUE THREAD

**Issue by muji92** [nicoDs96/btc-flashing-demo#2]
This is the error Mr how to solve?. Please help
[17302246475678428025292819142753](https://github.com/user-attachments/assets/ff55fb73-a411-4b61-b7c4-afa1dfde5f42)

**Comment by muji92** [comment]
Please how to solve
![IMG_20241030_153604](https://github.com/user-attachments/assets/8e4fc4af-c253-4a41-bd41-08bd2a351025)

**Comment by nicoDs96** [comment]
And I am the flying donkey... If you do it for learning then study how the protocol works starting from [the material I gave you in the previus issue](https://github.com/nicoDs96/btc-flashing-demo/issues/1#issuecomment-2444292749), after some time you will figure it out.
