### ISSUE TITLE
I just need help how to solve

### ISSUE THREAD

**Issue by muji92** [nicoDs96/btc-flashing-demo#3]
I have 1 UTXO and your script cant run , how to solved this i was get btc testnet coin but error' showing up
![IMG_20241030_153604](https://github.com/user-attachments/assets/06332e6d-c52f-48fa-b982-2838f97a4045)

**Comment by muji92** [comment]
I Will donate if problem solved

**Comment by muji92** [comment]
Send your btc address email me on hardjie92@gmail.com

**Comment by nicoDs96** [comment]
Load testnet coin on the wallet, you need cash to send cash

**Comment by muji92** [comment]
How to load ? i have 0.01 tbtc on wallet ... should i change the code?

**Comment by Zoekerin** [comment]
Hello @muji92 
Has your issues been resolved?
