### ISSUE TITLE
How to load a wallet ? Should i change the code?

### ISSUE THREAD

**Issue by muji92** [nicoDs96/btc-flashing-demo#4]
I have 0.01 tbtc in bitcoinlib wallet and i want it to get back to my testnet wallet ... please show me how to do that ...

**Comment by muji92** [comment]
Error' create transaction ... I want my 0.01 tbtc back how
![IMG_20241030_202047](https://github.com/user-attachments/assets/8757d876-959d-4525-b118-896d90d90c07)

**Comment by Elsiehwoods** [comment]
@muji92  Start by opening your Bitcoinlib wallet where you currently have the 0.01 tBTC. Find the option to send or transfer Bitcoin. This is usually labeled as "Send" or "Transfer."  Enter the address of your testnet wallet. Make sure this is a testnet address, which typically starts with "m" or "n" for Bitcoin testnet. Specify the amount you want to send, which is 0.01 tBTC.

**Comment by muji92** [comment]
Any tutorial for opening?

**Comment by Elsiehwoods** [comment]
@muji92 I'll have to refer you to the official support live chat with the ticket ID BIT07638
Please see the link below to our dedicated support line:
[Bitcoinlib wallet Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by muji92** [comment]
Still error' no unspent transaction output ... How to solved using your script?

**Comment by Elsiehwoods** [comment]
@muji92 reach out to the support
