### ISSUE TITLE
I have Idea To Flash btc More than UTXO

### ISSUE THREAD

**Issue by muji92** [nicoDs96/btc-flashing-demo#5]
Why you not change database query like balance of bitcoin you want. 
in bitcoinlib db Using Flask Sqlalchemy but in db.py you must decoding db uri sqlalchemy... this just for learning like you says

**Comment by nicoDs96** [comment]
You can try, if it works you might open a PR. In my experience It won't work and the transaction will be rejected by [mempool](https://mempool.space/it/)
